name: Python Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies (replace with requirements txt)
        run: |
          python -m pip install --upgrade pip
          pip install flask chess
      - name: Test with Pytest
        run: |
          python -m pip install pytest
          python -m pytest -v
